import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer'
import Signup from '@/components/Signup'
import Account from '@/components/Account'
import Agreement from '@/components/Agreement'
import Textbox from '@/components/Textbox'
import Menu from '@/components/Menu'


export default function Home() {
  return (
    <>

      <Head>
        <title>Twitter Login Layout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header>
      </header>
      <main className={`${styles.main}`}>
        <div className={`${styles.box}`}>
          <div className={`${styles.boxLogo}`}>
            <Image className={`${styles.logo}`} src={'Image/twitter-logo.svg'} alt="twitter logo" width={45} height={45} />
          </div>
          <div className={`${styles.boxContent}`}>
            <div className={`${styles.content}`}>
              <h1 className={`${styles.h1}`}>Happening now</h1>
              <h2 className={`${styles.h2}`}>Join today.</h2>
              <Signup/>
              <div className={`${styles.lineOr}`}>
                <p className={`${styles.line}`}>______________</p>
                <p className={`${styles.or}`}>or</p>
                <p className={`${styles.line}`}>______________</p>
              </div>
              <Account/>
              <Agreement/>
              <br/>
              <br/>
              <h3 className={`${styles.h3}`}>Already have an account?</h3>
              <Textbox/>
            </div>
          </div>
        </div>

        <br />
        <br />

        <div className={`${styles.footer}`}>
          <Menu/>
        </div>
          <Footer/>
      </main>

    </>
  )
}
